### ISSUE TITLE
Merge conflicts

### ISSUE THREAD

**Issue by aric87** [bpcoxjr/bruce-cox-portfolio#3]
Make sure you clean these out, especially the master branch. Potential employers aren't going to go looking at all the branches to find the most recent> They will look at the default: 
https://github.com/bpcoxjr/bruce-cox-portfolio/blob/master/index.html#L1
https://github.com/bpcoxjr/bruce-cox-portfolio/blob/master/index.html#L58
https://github.com/bpcoxjr/bruce-cox-portfolio/blob/master/index.html#L144
https://github.com/bpcoxjr/bruce-cox-portfolio/blob/master/css/style.css#L54

**Comment by bpcoxjr** [comment]
Fixed.
